Split opflex-agents into their own services
noironetworks/tripleo-ciscoaci pull request #62
Opened 2021-05-14 15:00 UTC by tbachman

The opflex-agent and neutron-opflex-agent are split out into
their own services (and therefore containers).

2021-05-14 15:00 UTC, tbachman commented
Don't merge yet - I need to test this with the ciscoaci-puppet changes first.

2021-05-14 15:43 UTC, ansao-aci commented on tripleo-ciscoaci/deployment/neutron_opflex/neutron-opflex-agent-container-puppet.yaml
> +                  - /var/log/containers/neutron:/var/log/neutron
We need the shared volume changes (used for sharing ep files and notification- socket) as well in both 
neutron-opflex-agent-container-puppet.yaml and opflex-agent-container-puppet.yaml files. 

Pls see here:
https://github.com/noironetworks/tripleo-ciscoaci/pull/43/files#diff-c23d17d0e76333d46a2ee1190520c4b9826846f16dd711d4956bdd126312242cR132-R133

2021-05-14 15:51 UTC, ansao-aci commented on tripleo-ciscoaci/deployment/neutron_opflex/neutron-opflex-agent-container-puppet.yaml
> +            image: {get_param: ContainerNeutronOpflexAgentImage}
Image name should be same as the one in  build_openstack_aci_containers.py script,  which is   DockerNeutronOpflexAgentImage.

2021-05-14 16:00 UTC, ansao-aci requested changes
1.   Image name is incorrect in the new container  yaml file.
2.  Changed for shared volume between the two containers is missing in both container's yaml file.

2021-05-14 16:24 UTC, tbachman commented
Both good catches! I just pushed an update that hopefully addresses both of these issues.

2021-05-14 16:34 UTC, irathore approved these changes

2021-05-18 09:56 UTC, tbachman commented
Pushed changes, and tested. Ready for review.

2021-05-18 22:13 UTC, merged